# Site
repository: p15bala/cv-1
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Daniel Balampanidis
title: Student at Ionian University
email: p15bala@ionio.gr
website: https://github.com/p15bala/cv-1

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  p15bala
linkedin_username: danielbalampanidis


# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Daniel and I'm a student in the Department of Informatics at Ionian University.

  I am most skilled in: <mark>Java</mark> and <mark>mySQL</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title:Bachelor Thesis 
        
        quote: >
          This is what I'm currently working on for my thesis.
        description: | # this will include new lines to allow paragraphs
          I'm developing an archaeological Database with Geographical Information and an online user interface. I have learned many skills through this,escpecially on Databases and web development.


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Ionian University
        caption: 2015 - Present
        sub_title: BS Information Technology
        
        description: | # this will include new lines to allow paragraphs
          During my time at Ionian University I have learned most of my key skills that I will use later on.


  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in Java and Databases some of my other interests and hobbies are:
      - Exploring new places
      - Going on Road Trips
      - Gaming
      - Video Editing
      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
